[options]
admin_passwd = admin15
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/addons-dev-15
data_dir = /var/lib/odoo
session_dir = /var/lib/odoo/sessions